# fly.toml app configuration file generated for datingapp-ekran on 2023-10-31T11:45:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp-ekran"
primary_region = "mad"

[build]
  image = "ekrandl/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dxyi5ophf"
  CloudinarySettings__ApiKey="381265878852652"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
